# Generated by Django 4.2.3 on 2023-07-22 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_champion_delete_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='champion',
            old_name='descrption',
            new_name='description',
        ),
    ]
